/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

import br.com.login.controller.LoginController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author gpatr
 */
public class CadastroView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroView
     */
    public CadastroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JTextField();
        nome2 = new javax.swing.JTextField();
        senha2 = new javax.swing.JPasswordField();
        botao3 = new javax.swing.JButton();
        fundo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setBackground(new java.awt.Color(153, 153, 153));
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 210, 30));

        nome2.setBackground(new java.awt.Color(153, 153, 153));
        nome2.setForeground(new java.awt.Color(255, 255, 255));
        nome2.setBorder(null);
        getContentPane().add(nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 210, 30));

        senha2.setBackground(new java.awt.Color(153, 153, 153));
        senha2.setForeground(new java.awt.Color(255, 255, 255));
        senha2.setBorder(null);
        getContentPane().add(senha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 210, 30));

        botao3.setContentAreaFilled(false);
        botao3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });
        getContentPane().add(botao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 220, 40));

        fundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/2.jpg"))); // NOI18N
        fundo2.setText("jLabel1");
        getContentPane().add(fundo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
        LoginController cadastro = new LoginController();
       if(nome2.getText().matches("") || email.getText().matches("") || senha2.getText().matches("")){
           JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos");
              
} else {

            try {            
            cadastro.cadastroUsuario(this);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroView.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso!");
        this.setVisible(false);
           
}
        
        
        
    }//GEN-LAST:event_botao3ActionPerformed

    public JTextField getEmail() {
        return email;
    }

    public void setEmail(JTextField email) {
        this.email = email;
    }

    public JTextField getNome2() {
        return nome2;
    }

    public void setNome2(JTextField nome2) {
        this.nome2 = nome2;
    }

    public JPasswordField getSenha2() {
        return senha2;
    }

    public void setSenha2(JPasswordField senha2) {
        this.senha2 = senha2;
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao3;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fundo2;
    private javax.swing.JTextField nome2;
    private javax.swing.JPasswordField senha2;
    // End of variables declaration//GEN-END:variables
}
