/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.principal.view;

/**
 *
 * @author gpatr
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    public TelaPrincipalView() {
        initComponents();
        setExtendedState(MAXIMIZED_VERT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JButton();
        features = new javax.swing.JButton();
        shortcodes = new javax.swing.JButton();
        posttypes = new javax.swing.JButton();
        shop = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 30, 20));

        features.setContentAreaFilled(false);
        features.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(features, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 40, 20));

        shortcodes.setContentAreaFilled(false);
        shortcodes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(shortcodes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 50, 20));

        posttypes.setContentAreaFilled(false);
        posttypes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        posttypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posttypesActionPerformed(evt);
            }
        });
        getContentPane().add(posttypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 50, 20));

        shop.setContentAreaFilled(false);
        shop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(shop, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 30, 20));

        menu.setContentAreaFilled(false);
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 60, 20));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Pizza-Restaurant-themes-wordpress-creer-site-web-pizzeria-restaurant-boulangerie-vendre-pizza(1).jpg"))); // NOI18N
        fundo.setText("jLabel1");
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
       menu telaDeMenu = new menu();
       telaDeMenu.setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void posttypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posttypesActionPerformed
        post_types telaDeImagem = new post_types();
        telaDeImagem.setVisible(true);
    }//GEN-LAST:event_posttypesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton features;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton home;
    private javax.swing.JButton menu;
    private javax.swing.JButton posttypes;
    private javax.swing.JButton shop;
    private javax.swing.JButton shortcodes;
    // End of variables declaration//GEN-END:variables
}
