/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

import br.com.login.controller.LoginController;
import br.com.principal.view.TelaPrincipalView;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author gpatr
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new javax.swing.JTextField();
        botão = new javax.swing.JButton();
        senha = new javax.swing.JPasswordField();
        botão2 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setBackground(new java.awt.Color(143, 142, 142));
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setBorder(null);
        usuario.setCaretColor(new java.awt.Color(143, 142, 142));
        usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usuario.setDisabledTextColor(new java.awt.Color(143, 142, 142));
        usuario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                usuarioPropertyChange(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 210, 30));

        botão.setContentAreaFilled(false);
        botão.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoActionPerformed(evt);
            }
        });
        getContentPane().add(botão, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 190, 30));

        senha.setBackground(new java.awt.Color(143, 142, 142));
        senha.setForeground(new java.awt.Color(255, 255, 255));
        senha.setBorder(null);
        senha.setCaretColor(new java.awt.Color(143, 142, 142));
        senha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        senha.setDisabledTextColor(new java.awt.Color(143, 142, 142));
        senha.setHighlighter(null);
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 210, 30));

        botão2.setContentAreaFilled(false);
        botão2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botão2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão2ActionPerformed(evt);
            }
        });
        getContentPane().add(botão2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 150, 30));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1.jpg"))); // NOI18N
        fundo.setText("jLabel3");
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_usuarioPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioPropertyChange

    private void botão2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão2ActionPerformed
        CadastroView telaDeCadastro = new CadastroView();
        telaDeCadastro.setVisible(true);
    }//GEN-LAST:event_botão2ActionPerformed

    private void botãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoActionPerformed
        LoginController login = new LoginController();
        
        if(usuario.getText().matches("")  || senha.getText().matches("")){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos");
        
        } else {
            try {
            login.loginUsuario(this);
        } catch (SQLException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
            TelaPrincipalView telaPrincipal = new TelaPrincipalView();
            telaPrincipal.setVisible(true);
            
            
        }
    }//GEN-LAST:event_botãoActionPerformed

    public JPasswordField getSenha() {
        return senha;
    }

    public void setSenha(JPasswordField senha) {
        this.senha = senha;
    }

    public JTextField getUsuario() {
        return usuario;
    }

    public void setUsuario(JTextField usuario) {
        this.usuario = usuario;
    }

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botão;
    private javax.swing.JButton botão2;
    private javax.swing.JLabel fundo;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
